version: 2
jobs:
  build:
    working_directory: ~/ShoppingCarts
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

      release-build:
        executor:
          name: android/android-machine
          resource-class: xlarge
        steps:
          - checkout
          - android/restore-gradle-cache
          - android/restore-build-cache
          - run:
              name: Assemble release build
              command: |
                ./gradlew assembleRelease
          - store_artifacts:
              path: app/build/outputs/apk/release